### ISSUE TITLE
How can modelsim recognize that 18'b000000000000000110 is 0.02 instead of 6 during the simulation process?

### ISSUE THREAD

**Issue by Steven0007** [naveen-chander/biorealistic-spiking-neural-network#1]
How can modelsim recognize that 18'b000000000000000110 is 0.02 instead of 6 during the simulation process? I used your uv_fsm code to simulate in modelsim and did not produce your first graph in the report. The output spike is always 0. Can you answer it? Thank you!

**Comment by naveen-chander** [comment]
Fixed point Q(18,8) is used to represent all numbers (indicated near fig.1 in report). So, the number in the question becomes 2^-6 + 2^-7 , which is roughly 0.02. 
********************************************************
uv_fsm is not the top module. Many of the inputs to the uv_fsm are automatically computed and supplied to the uv_fsm in the top module. 

Directly supplying inputs to the uv_fsm requires us to manually generate the correct sequence of of u_n, v_n, which is tricky and not provided in the repo.

The tb_top.v on the other hand, is intended to test the Neuron as a whole and produces spikes in presence of a sufficient spiking current, such as the value provided in the test bench.

Thus, I would recommend the usage of tb_top.v and simulate the top module to observe spikes. 

FYI, the spikes first graph are obtained using  tb_top.v.
uv_fsm_tb can at best, be used to observe fsm state transitions.

**Comment by Steven0007** [comment]
Thank you for answering my doubts in your busy schedule! Thank you very much!
